require 'rainbow'
require_relative './board'
require_relative './player'
require_relative './human_player'
require_relative './computer_player'
require_relative './renderer'
require_relative './master_mind'